### ISSUE TITLE
RuntimeError: Backend "sox_io" is not one of available backends: ['soundfile'].

### ISSUE THREAD

**Issue by TimLeeCV** [MStypulkowski/diffused-heads#26]
RuntimeError: Backend "sox_io" is not one of available backends: ['soundfile'].

**Comment by MStypulkowski** [comment]
Can you provide a full error trace?

**Comment by TimLeeCV** [comment]
> Can you provide a full error trace?


Traceback (most recent call last):
  File "C:\Users\10491\Desktop\diffused-heads-main\sample.py", line 5, in <module>
    from utils import get_id_frame, get_audio_emb, save_video
  File "C:\Users\10491\Desktop\diffused-heads-main\utils.py", line 17, in <module>
    torchaudio.set_audio_backend("sox_io")
  File "D:\ProgramData\Anaconda3\envs\test\lib\site-packages\torchaudio\backend\utils.py", line 40, in set_audio_backend
    raise RuntimeError(f'Backend "{backend}" is not one of ' f"available backends: {list_audio_backends()}.")
RuntimeError: Backend "sox_io" is not one of available backends: ['soundfile'].

Thanks！

**Comment by MStypulkowski** [comment]
Since you are using Windows, try changing `torchaudio.set_audio_backend("sox_io")` to `torchaudio.set_audio_backend("soundfile")`.

**Comment by TimLeeCV** [comment]
> Since you are using Windows, try changing `torchaudio.set_audio_backend("sox_io")` to `torchaudio.set_audio_backend("soundfile")`.

Thanks for your reply！

**Comment by TimLeeCV** [comment]
When I solved that problem, I had the following problem.

Loading model...
Error executing job with overrides: []
Traceback (most recent call last):
  File "C:\Users\10491\Desktop\diffused-heads-main\sample.py", line 18, in main
    audio, audio_emb = get_audio_emb(args.audio, args.encoder_checkpoint, device)
  File "C:\Users\10491\Desktop\diffused-heads-main\utils.py", line 46, in get_audio_emb
    emb = audio_encoder(audio)
  File "D:\ProgramData\Anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\10491\Desktop\diffused-heads-main\utils.py", line 31, in forward
    emb, _, self.hidden = self.model(x[:, i], torch.LongTensor([3200]), init_state=self.hidden)
  File "D:\ProgramData\Anaconda3\envs\test\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: forward() is missing value for argument 'x_cond'. Declaration: forward(__torch__.models.unet.UNet self, Tensor x, Tensor timesteps, Tensor x_cond, Tensor motion_frames, Tensor audio_emb) -> (Tensor)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by MStypulkowski** [comment]
Either `torchaudio.load()` in `get_audio_emb()` doesn't work correctly or there's a problem with scripted models when using them on Windows. Our model was only tested on Linux.

**Comment by TimLeeCV** [comment]
Thank you! I'll try it on Linux.
